# Environtment for local development and testing
version: "3.1"

services:
  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: runtask
      POSTGRES_PASSWORD: runtask
      POSTGRES_DB: runtask
    # Persistent data in the project folder
    volumes:
      - ~/dev/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
